# Generated by Django 2.1.7 on 2019-03-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0002_addsignup_potentia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsignup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to=settings.AUTH_USER_MODEL),
        ),
    ]
