# Generated by Django 2.1.7 on 2019-03-28 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('sent_transfer_tx', models.TextField(null=True)),
                ('sent_creation_tx', models.TextField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('tosenduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tosenduser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
